export const TOURS = [
  { name: 'Trekking & Hiking', href: '/en/tours/trekking' },
  { name: 'Biking',            href: '/en/tours/biking' },
  { name: 'Caving',            href: '/en/tours/caving' },
  { name: 'Canyoning',         href: '/en/tours/canyoning' },
  { name: 'Overlanding',       href: '/en/tours/overlanding' },
  { name: 'Mixed Tours',       href: '/en/tours/mixed-tours' },
  { name: 'Summit Experience', href: '/en/tours/summit-experience' },
  { name: 'Climbing',          href: '/en/tours/climbing' },
] as const

export const SERVICES = [
  { label: 'Custom Trip Planning', soon: false },
  { label: 'Transfers & Logistics', soon: false },
  { label: 'Climbing Course', soon: true },
  { label: 'Children Camp', soon: true },
  { label: 'Rope Training', soon: true },
  { label: 'Winter Sports', soon: true },
] as const

export const ACTIVITIES = [
  { id: 'trekking',   name: 'Trekking & Hiking',   image: '/images/svaneti.jpg',  gradient: 'linear-gradient(160deg,#0e2018 0%,#1a3a28 100%)' },
  { id: 'biking',     name: 'Biking',               image: null,                   gradient: 'linear-gradient(160deg,#241a0e 0%,#3d2e10 100%)' },
  { id: 'caving',     name: 'Caving',               image: null,                   gradient: 'linear-gradient(160deg,#0d0d0b 0%,#201e18 100%)' },
  { id: 'canyoning',  name: 'Canyoning',            image: '/images/martvili.jpg', gradient: 'linear-gradient(160deg,#0c1e2a 0%,#163248 100%)' },
  { id: 'overlanding', name: 'Overlanding',         image: null,                   gradient: 'linear-gradient(160deg,#28180a 0%,#4a2e0e 100%)' },
  { id: 'mixed',      name: 'Mixed Tours',          image: null,                   gradient: 'linear-gradient(160deg,#241208 0%,#62291a 100%)' },
  { id: 'summit',     name: 'Summit Experience',    image: '/images/kazbegi.jpg',  gradient: 'linear-gradient(160deg,#0a1422 0%,#1e2e48 100%)' },
  { id: 'climbing',   name: 'Climbing',             image: null,                   gradient: 'linear-gradient(160deg,#141a0c 0%,#2a3418 100%)' },
]

export const FEATURED_TOURS = [
  {
    id: 'ice-and-towers-svaneti',
    href: '/en/tours/ice-and-towers-svaneti',
    image: '/images/tours/ice-towers-hero.avif',
    name: 'Ice and Towers, Svaneti',
    hook: 'Glaciers, medieval towers & high passes',
    region: 'Svaneti',
    activity: 'Trekking & Hiking',
    duration: '9 days',
    difficulty: 'Moderate',
    price: '€2,490',
    badge: 'New',
  },
  {
    id: 'chaukhi-mountaineering-camp',
    href: '/en/tours/chaukhi-mountaineering-camp',
    image: '/images/tours/summit/chaukhi-ridge-team.jpg',
    name: 'Chaukhi Massif Mountaineering Camp',
    hook: 'Learn the ropes in the "Georgian Dolomites"',
    region: 'Kazbegi',
    activity: 'Summit Experience',
    duration: '8 days',
    difficulty: 'Challenging',
    price: '€1,500',
    badge: 'New',
  },
  {
    id: 'trans-georgia-tbilisi-batumi',
    href: '/en/tours/trans-georgia-tbilisi-batumi',
    image: '/images/tours/biking/trans-georgia-hero.jpg',
    name: 'Trans-Georgia Traverse: Tbilisi to the Black Sea',
    hook: 'Cross a country by bike — capital to coast',
    region: 'Tbilisi → Batumi',
    activity: 'Biking',
    duration: '7 days',
    difficulty: 'Challenging',
    price: '€1,276',
    badge: 'New',
  },
  {
    id: 'canyoning-day-adventure',
    href: '/en/tours/canyoning-day-adventure',
    image: '/images/tours/canyoning/canyoning-waterfall-rappel.jpg',
    name: 'Canyoning Day Adventure',
    hook: 'Rappel waterfalls & jump green pools',
    region: 'Imereti',
    activity: 'Canyoning',
    duration: '1 day',
    difficulty: 'Moderate',
    price: '€110',
    badge: 'New',
  },
  {
    id: 'vashlovani-overland-expedition',
    href: '/en/tours/vashlovani-overland-expedition',
    image: '/images/tours/overlanding/dg-05.jpg',
    name: 'Vashlovani Semi-Desert Overland',
    hook: 'Canyons, mud volcanoes & big skies',
    region: 'Kakheti',
    activity: 'Overlanding',
    duration: '7 days',
    difficulty: 'Moderate',
    price: '€600',
    badge: 'New',
  },
  {
    id: 'overland-guria-adjara',
    href: '/en/tours/overland-guria-adjara',
    image: '/images/tours/overlanding/dg-06.jpg',
    name: 'Overland: Guria & Adjara',
    hook: 'Cloud-kingdoms & hidden alpine lakes',
    region: 'Adjara',
    activity: 'Overlanding',
    duration: '7 days',
    difficulty: 'Moderate',
    price: '€800',
    badge: 'New',
  },
  {
    id: 'melouri-cave-caving',
    href: '/en/tours/melouri-cave-caving',
    image: '/images/tours/caving/melouri-river-passage.jpg',
    name: 'Wild Caving in Melouri Cave',
    hook: 'Wade an underground river by headlamp',
    region: 'Imereti',
    activity: 'Caving',
    duration: '1 day',
    difficulty: 'Moderate',
    price: '€95',
    badge: 'New',
  },
  {
    id: 'discover-georgia-local',
    href: '/en/tours/discover-georgia-as-a-local',
    image: '/images/tours/overlanding/dg-04.jpg',
    name: 'Discover Georgia as a Local',
    hook: 'Ten days, one 4x4, the whole country',
    region: 'Multi-Region',
    activity: 'Overlanding',
    duration: '10 days',
    difficulty: 'Moderate',
    price: '€1,000',
    badge: 'New',
  },
]

export const GUIDES = [
  {
    id: 'tamo',
    name: 'Tamo',
    role: 'Founder & Lead Mountain Guide',
    bio: 'UIMLA-certified with 10+ years across the Caucasus. Happiest on a ridge line with a thermos of coffee.',
    cert: 'UIMLA Certified',
    langs: 'English · ქართული · Русский',
    photo: '/images/guides/tamo.jpg',
    alt: 'Tamo, lead mountain guide for Adventure Experts Georgia',
  },
  {
    id: 'cotne',
    name: 'Cotne',
    role: 'Climbing & Caving Guide',
    bio: 'Wilderness first responder who knows the caves of Imereti better than anyone alive.',
    cert: 'Wilderness First Responder',
    langs: 'English · ქართული',
    photo: '/images/guides/cotne.png',
    alt: 'Cotne, climbing and caving guide for Adventure Experts Georgia',
  },
  {
    id: 'rezi',
    name: 'Rezi',
    role: 'Trekking & Overlanding Guide',
    bio: 'Born in Svaneti. Drives the wildest 4x4 routes and tells the best campfire stories.',
    cert: 'Off-Road & First Aid',
    langs: 'English · ქართული · Русский',
    photo: '/images/guides/rezi.jpg',
    alt: 'Rezi, trekking and overlanding guide for Adventure Experts Georgia',
  },
]

export const REGIONS = [
  { id: 'svaneti', name: 'Svaneti', activities: ['Trekking & Hiking', 'Climbing', 'Mixed Tours'] },
  { id: 'kazbegi', name: 'Kazbegi', activities: ['Trekking & Hiking', 'Summit Experience', 'Climbing'] },
  { id: 'imereti', name: 'Imereti', activities: ['Caving', 'Canyoning', 'Day Tours'] },
  { id: 'kakheti', name: 'Kakheti', activities: ['Mixed Tours', 'Biking', 'Day Tours'] },
  { id: 'adjara', name: 'Adjara', activities: ['Trekking & Hiking', 'Mixed Tours'] },
  { id: 'racha', name: 'Racha', activities: ['Overlanding', 'Trekking & Hiking'] },
]
