export const TOURS = [
  'Trekking & Hiking',
  'Biking',
  'Caving',
  'Canyoning',
  'Overlanding',
  'Mixed Tours',
  'Summit Experience',
  'Climbing',
] as const

export const SERVICES = [
  { label: 'Custom Trip Planning', soon: false },
  { label: 'Transfers & Logistics', soon: false },
  { label: 'Climbing Course', soon: true },
  { label: 'Children Camp', soon: true },
  { label: 'Rope Training', soon: true },
  { label: 'Winter Sports', soon: true },
] as const

export const ACTIVITIES = [
  { id: 'trekking',   name: 'Trekking & Hiking',   image: '/images/svaneti.jpg',  gradient: 'linear-gradient(160deg,#0e2018 0%,#1a3a28 100%)' },
  { id: 'biking',     name: 'Biking',               image: null,                   gradient: 'linear-gradient(160deg,#241a0e 0%,#3d2e10 100%)' },
  { id: 'caving',     name: 'Caving',               image: null,                   gradient: 'linear-gradient(160deg,#0d0d0b 0%,#201e18 100%)' },
  { id: 'canyoning',  name: 'Canyoning',            image: '/images/martvili.jpg', gradient: 'linear-gradient(160deg,#0c1e2a 0%,#163248 100%)' },
  { id: 'overlanding', name: 'Overlanding',         image: null,                   gradient: 'linear-gradient(160deg,#28180a 0%,#4a2e0e 100%)' },
  { id: 'mixed',      name: 'Mixed Tours',          image: null,                   gradient: 'linear-gradient(160deg,#241208 0%,#62291a 100%)' },
  { id: 'summit',     name: 'Summit Experience',    image: '/images/kazbegi.jpg',  gradient: 'linear-gradient(160deg,#0a1422 0%,#1e2e48 100%)' },
  { id: 'climbing',   name: 'Climbing',             image: null,                   gradient: 'linear-gradient(160deg,#141a0c 0%,#2a3418 100%)' },
]

export const FEATURED_TOURS = [
  {
    id: 'svaneti',
    href: '/en/tours/svaneti-glacier-trek',
    image: '/images/svaneti.jpg',
    name: 'Svaneti Glacier Trek',
    hook: 'Glacier views & ancient towers',
    region: 'Svaneti',
    activity: 'Trekking & Hiking',
    duration: '4 days',
    difficulty: 'Moderate',
    price: '€690',
    badge: 'New',
  },
  {
    id: 'kazbegi',
    href: '/en/tours/kazbegi-summit-adventure',
    image: '/images/kazbegi.jpg',
    name: 'Kazbegi Summit Adventure',
    hook: 'Stand on a 5,000m peak',
    region: 'Kazbegi',
    activity: 'Summit Experience',
    duration: '6 days',
    difficulty: 'Challenging',
    price: '€1,150',
    badge: 'New',
  },
  {
    id: 'martvili',
    href: '/en/tours/martvili-canyon-day-trip',
    image: '/images/martvili.jpg',
    name: 'Martvili Canyon Day Trip',
    hook: 'Turquoise water & cliffs',
    region: 'Imereti',
    activity: 'Canyoning',
    duration: '1 day',
    difficulty: 'Easy',
    price: '€95',
    badge: 'New',
  },
  {
    id: 'kakheti',
    href: '/en/tours/kakheti-wine-and-trails',
    image: '/images/svaneti.jpg',
    name: 'Kakheti Wine & Trails',
    hook: 'Vineyards, forts & open sky',
    region: 'Kakheti',
    activity: 'Mixed Tours',
    duration: '3 days',
    difficulty: 'Easy',
    price: '€420',
    badge: 'New',
  },
  {
    id: 'racha',
    href: '/en/tours/racha-overlanding',
    image: '/images/kazbegi.jpg',
    name: 'Racha 4×4 Overlanding',
    hook: 'Remote valleys, no tourist path',
    region: 'Racha',
    activity: 'Overlanding',
    duration: '5 days',
    difficulty: 'Moderate',
    price: '€880',
    badge: 'New',
  },
  {
    id: 'prometheus',
    href: '/en/tours/prometheus-cave-imereti',
    image: '/images/martvili.jpg',
    name: 'Prometheus Cave & Imereti',
    hook: 'Georgia\'s greatest underground world',
    region: 'Imereti',
    activity: 'Caving',
    duration: '1 day',
    difficulty: 'Easy',
    price: '€80',
    badge: 'New',
  },
]

export const GUIDES = [
  {
    id: 'tamo',
    name: 'Tamo',
    role: 'Founder & Lead Mountain Guide',
    bio: 'UIMLA-certified with 10+ years across the Caucasus. Happiest on a ridge line with a thermos of coffee.',
    cert: 'UIMLA Certified',
    langs: 'English · ქართული · Русский',
    photo: '/images/guides/tamo.jpg',
    alt: 'Tamo, lead mountain guide for Adventure Experts Georgia',
  },
  {
    id: 'cotne',
    name: 'Cotne',
    role: 'Climbing & Caving Guide',
    bio: 'Wilderness first responder who knows the caves of Imereti better than anyone alive.',
    cert: 'Wilderness First Responder',
    langs: 'English · ქართული',
    photo: '/images/guides/cotne.png',
    alt: 'Cotne, climbing and caving guide for Adventure Experts Georgia',
  },
  {
    id: 'rezi',
    name: 'Rezi',
    role: 'Trekking & Overlanding Guide',
    bio: 'Born in Svaneti. Drives the wildest 4x4 routes and tells the best campfire stories.',
    cert: 'Off-Road & First Aid',
    langs: 'English · ქართული · Русский',
    photo: '/images/guides/rezi.jpg',
    alt: 'Rezi, trekking and overlanding guide for Adventure Experts Georgia',
  },
]

export const REVIEWS = [
  {
    id: 1,
    stars: 5,
    quote:
      'Completely exceeded our expectations. Giorgi knew every trail, every ridge, every shortcut — and he introduced us to a shepherd family we\'d never have found on our own. The Svaneti trek was the best week of the year.',
    tour: 'Svaneti Glacier Trek',
    date: 'April 2026',
    name: 'Thomas R.',
    country: 'Germany',
    source: 'Google',
  },
  {
    id: 2,
    stars: 5,
    quote:
      'The Martvili day trip is stunning on its own but the guides made it unforgettable. They brought homemade churchkhela and told stories about the canyon that you can\'t find in any guide book.',
    tour: 'Martvili Canyon Day Trip',
    date: 'May 2026',
    name: 'Sophie L.',
    country: 'France',
    source: 'TripAdvisor',
  },
  {
    id: 3,
    stars: 5,
    quote:
      'I\'ve trekked in Nepal and Patagonia, but Georgia surprised me more than both. Small group, real guides, real food, real Georgia. Book with these guys — don\'t overthink it.',
    tour: 'Kazbegi Summit Adventure',
    date: 'June 2026',
    name: 'James K.',
    country: 'United Kingdom',
    source: 'Google',
  },
]

export const REGIONS = [
  { id: 'svaneti', name: 'Svaneti', activities: ['Trekking & Hiking', 'Climbing', 'Mixed Tours'] },
  { id: 'kazbegi', name: 'Kazbegi', activities: ['Trekking & Hiking', 'Summit Experience', 'Climbing'] },
  { id: 'imereti', name: 'Imereti', activities: ['Caving', 'Canyoning', 'Day Tours'] },
  { id: 'kakheti', name: 'Kakheti', activities: ['Mixed Tours', 'Biking', 'Day Tours'] },
  { id: 'adjara', name: 'Adjara', activities: ['Trekking & Hiking', 'Mixed Tours'] },
  { id: 'racha', name: 'Racha', activities: ['Overlanding', 'Trekking & Hiking'] },
]
